networks:
    backend:     

services:
    db:
        image: mysql:latest
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpressBBDD
            MYSQL_PASSWORD: A123456a
            MYSQL_ROOT_PASSWORD: A123456a
        volumes:
            - ./volumenes/db:/var/lib/mysql
        networks: 
            - backend
    wordpress:
        image: wordpress
        restart: always
        depends_on:
          - db
        ports:
          - 80:80
        environment:
          WORDPRESS_DB_HOST: db
          WORDPRESS_DB_USER: wordpressBBDD
          WORDPRESS_DB_PASSWORD: A123456a
          WORDPRESS_DB_NAME: wordpress
        volumes:
          - ./volumenes/wordpress:/var/www/html
        networks: 
            - backend    
